# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alarmclock.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 441))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lblTime = QtWidgets.QLabel(self.tab)
        self.lblTime.setGeometry(QtCore.QRect(290, 120, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.lblTime.setFont(font)
        self.lblTime.setObjectName("lblTime")
        self.lblDate = QtWidgets.QLabel(self.tab)
        self.lblDate.setGeometry(QtCore.QRect(260, 200, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.lblDate.setFont(font)
        self.lblDate.setObjectName("lblDate")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(390, 110, 191, 141))
        self.groupBox.setObjectName("groupBox")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(10, 30, 70, 17))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(100, 30, 70, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 60, 70, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setGeometry(QtCore.QRect(100, 60, 70, 17))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_5.setGeometry(QtCore.QRect(10, 90, 70, 17))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_6.setGeometry(QtCore.QRect(100, 90, 70, 17))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_7.setGeometry(QtCore.QRect(60, 120, 70, 17))
        self.checkBox_7.setObjectName("checkBox_7")
        self.btnSet = QtWidgets.QPushButton(self.tab_2)
        self.btnSet.setGeometry(QtCore.QRect(390, 260, 75, 23))
        self.btnSet.setObjectName("btnSet")
        self.btnDelete = QtWidgets.QPushButton(self.tab_2)
        self.btnDelete.setGeometry(QtCore.QRect(510, 260, 75, 23))
        self.btnDelete.setObjectName("btnDelete")
        self.txtName = QtWidgets.QPlainTextEdit(self.tab_2)
        self.txtName.setGeometry(QtCore.QRect(390, 40, 191, 31))
        self.txtName.setObjectName("txtName")
        self.tAlarmTime = QtWidgets.QTimeEdit(self.tab_2)
        self.tAlarmTime.setGeometry(QtCore.QRect(390, 80, 191, 22))
        self.tAlarmTime.setObjectName("tAlarmTime")
        self.lvAlarmList = QtWidgets.QListWidget(self.tab_2)
        self.lvAlarmList.setGeometry(QtCore.QRect(0, 0, 191, 421))
        self.lvAlarmList.setObjectName("lvAlarmList")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblTime.setText(_translate("MainWindow", "TextLabel"))
        self.lblDate.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.checkBox.setText(_translate("MainWindow", "Monday"))
        self.checkBox_2.setText(_translate("MainWindow", "Tuesday"))
        self.checkBox_3.setText(_translate("MainWindow", "Wensday"))
        self.checkBox_4.setText(_translate("MainWindow", "Thursday"))
        self.checkBox_5.setText(_translate("MainWindow", "Friday"))
        self.checkBox_6.setText(_translate("MainWindow", "Saturday"))
        self.checkBox_7.setText(_translate("MainWindow", "Sunday"))
        self.btnSet.setText(_translate("MainWindow", "Set"))
        self.btnDelete.setText(_translate("MainWindow", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))

