# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alarmclockalt4.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(0, 0, 801, 431))
        self.toolBox.setObjectName("toolBox")
        self.toolBoxPage1 = QtWidgets.QWidget()
        self.toolBoxPage1.setGeometry(QtCore.QRect(0, 0, 801, 377))
        self.toolBoxPage1.setObjectName("toolBoxPage1")
        self.lblTime = QtWidgets.QLabel(self.toolBoxPage1)
        self.lblTime.setGeometry(QtCore.QRect(10, 120, 781, 71))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.lblTime.setFont(font)
        self.lblTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTime.setObjectName("lblTime")
        self.lblDate = QtWidgets.QLabel(self.toolBoxPage1)
        self.lblDate.setGeometry(QtCore.QRect(10, 200, 781, 71))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.lblDate.setFont(font)
        self.lblDate.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDate.setObjectName("lblDate")
        self.btnAddAlarm = QtWidgets.QPushButton(self.toolBoxPage1)
        self.btnAddAlarm.setGeometry(QtCore.QRect(740, 330, 41, 41))
        self.btnAddAlarm.setObjectName("btnAddAlarm")
        self.btnShowAlarms = QtWidgets.QPushButton(self.toolBoxPage1)
        self.btnShowAlarms.setEnabled(True)
        self.btnShowAlarms.setGeometry(QtCore.QRect(740, 280, 41, 41))
        self.btnShowAlarms.setObjectName("btnShowAlarms")
        self.lvAlarmList = QtWidgets.QListView(self.toolBoxPage1)
        self.lvAlarmList.setGeometry(QtCore.QRect(10, 0, 121, 371))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lvAlarmList.setFont(font)
        self.lvAlarmList.setAutoFillBackground(False)
        self.lvAlarmList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lvAlarmList.setObjectName("lvAlarmList")
        self.lblWeatherIcon = QtWidgets.QLabel(self.toolBoxPage1)
        self.lblWeatherIcon.setGeometry(QtCore.QRect(350, 0, 91, 71))
        self.lblWeatherIcon.setText("")
        self.lblWeatherIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWeatherIcon.setObjectName("lblWeatherIcon")
        self.lblHiLow = QtWidgets.QLabel(self.toolBoxPage1)
        self.lblHiLow.setGeometry(QtCore.QRect(10, 60, 781, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblHiLow.setFont(font)
        self.lblHiLow.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHiLow.setObjectName("lblHiLow")
        self.lblCurrent = QtWidgets.QLabel(self.toolBoxPage1)
        self.lblCurrent.setGeometry(QtCore.QRect(10, 80, 781, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblCurrent.setFont(font)
        self.lblCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCurrent.setObjectName("lblCurrent")
        self.lblTime.raise_()
        self.lblDate.raise_()
        self.btnAddAlarm.raise_()
        self.btnShowAlarms.raise_()
        self.lblWeatherIcon.raise_()
        self.lblHiLow.raise_()
        self.lblCurrent.raise_()
        self.lvAlarmList.raise_()
        self.toolBox.addItem(self.toolBoxPage1, "")
        self.toolBoxPage2 = QtWidgets.QWidget()
        self.toolBoxPage2.setGeometry(QtCore.QRect(0, 0, 801, 377))
        self.toolBoxPage2.setObjectName("toolBoxPage2")
        self.groupBox = QtWidgets.QGroupBox(self.toolBoxPage2)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 781, 191))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 131, 131))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(170, 20, 131, 131))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(320, 20, 131, 131))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(470, 20, 131, 131))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(620, 20, 131, 131))
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(20, 160, 131, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(170, 160, 131, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(320, 160, 131, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(470, 160, 131, 20))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(620, 160, 131, 20))
        self.label_15.setObjectName("label_15")
        self.groupBox_2 = QtWidgets.QGroupBox(self.toolBoxPage2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 200, 781, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 131, 131))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(170, 20, 131, 131))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(320, 20, 131, 131))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(470, 20, 131, 131))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(620, 20, 131, 131))
        self.label_10.setObjectName("label_10")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(20, 160, 131, 20))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(170, 160, 131, 20))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(320, 160, 131, 20))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(470, 160, 131, 20))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(620, 160, 131, 20))
        self.label_20.setObjectName("label_20")
        self.toolBox.addItem(self.toolBoxPage2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.lblTime.setText(_translate("MainWindow", "TextLabel"))
        self.lblDate.setText(_translate("MainWindow", "TextLabel"))
        self.btnAddAlarm.setText(_translate("MainWindow", "+"))
        self.btnShowAlarms.setText(_translate("MainWindow", "Alarms"))
        self.lblHiLow.setText(_translate("MainWindow", "Hi: 89 | Low: 60"))
        self.lblCurrent.setText(_translate("MainWindow", "Current: 89"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage1), _translate("MainWindow", "Clock"))
        self.groupBox.setTitle(_translate("MainWindow", "Hourly Forcast"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Daily Forcast"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "TextLabel"))
        self.label_17.setText(_translate("MainWindow", "TextLabel"))
        self.label_18.setText(_translate("MainWindow", "TextLabel"))
        self.label_19.setText(_translate("MainWindow", "TextLabel"))
        self.label_20.setText(_translate("MainWindow", "TextLabel"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage2), _translate("MainWindow", "Weather"))

